name: Python Package

on:
  push:
    branches:
      - master
      - unstable
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} and ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=100 --max-line-length=200 --statistics
    - name: Build the pypi package
      run: |
        # build 
        python setup.py sdist
